### ISSUE TITLE
Import / export to JSON file

### ISSUE THREAD

**Issue by ojurkiewicz** [krzysztofrewak/powiaty#1]
Hey,
Thanks for the cool project. One uncomfortable thing that came out when using it is having to manually enter data if you want to update the map. It is nice, that there is a browser cache, but it is not very practical when changing computers, browsers or just clearing the cache. 

I suggest importing to JSON file. I had a quick look at the code and since there is already an established pattern of creating cache in localstorage there is no point in changing it, just allow to export it at any time and overwrite the current state with a JSON file. 

If you are open to this feature I can open a pull request in my spare time.

Cheers

**Comment by krzysztofrewak** [comment]
Hi, @ojurkiewicz! Quick and ugly solution would be to copypaste localstorage value. ;)

But if you'd like to contribute, feel free to open you PR.
